repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        pass_filenames: false
        fail_fast: true

      - id: cargo-test
        name: cargo test
        entry: cargo test -- --test-threads=1
        language: system
        pass_filenames: false
        fail_fast: true

  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.16.0
