[workspace]
members = [".", "envro-derive", "example"]
resolver = "2"

[workspace.package]
version = "0.10.0"

[package]
name = "envro"
version.workspace = true
edition = "2021"
description = "A crate to load environment variables from a .env file into the process environment variables"
license = "MIT"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
]

[dependencies]
thiserror = "^2.0.20"
envro-derive = { path = "envro-derive", version = "0.10.0" }

[dev-dependencies]
serial_test = "^4.0.1"
