name: ci

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.yaml'
      - '.gitignore'
      - 'example/**'
      - '.cz.toml'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yaml'
      - 'example/**'
      - '.cz.toml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: cargo test -- --test-threads=1
